const tags = {
  视觉效果: [
    '颜色',
    '背景',
    '边框',
    '阴影',
    '渐变',
    '变换',
    '过渡',
    '动画',
    '滤镜',
    '混合模式',
    '裁剪',
    '蒙版',
    '2D/3D变换',
    '文本效果',
    'light and dark theme'
  ],
  网页布局: [
    '网格',
    '弹性盒',
    '浮动',
    '定位',
    '自适应',
    '响应式',
    '媒体查询',
    '容器查询',
    '网格布局',
    '弹性盒布局',
    '浮动布局',
    '定位布局',
    '自适应布局',
    'Responsive Web Design',
    '媒体查询布局',
    '容器查询布局'
  ],
  'CSS 框架': ['Tailwind', 'Bootstrap', 'Foundation', 'Material UI', 'Bulma', 'Pure CSS', 'UIKit'],
  Vue: [
    'Vue 2',
    'Vue 3',
    'Vue Router',
    'Vuex',
    'Vue CLI',
    'Vue Devtools',
    'Vue Test Utils',
    'Vue Server Renderer',
    'Vue Native',
    'Vue Native CLI',
    'Vue Native Devtools',
    'Vue Native Test Utils',
    'Vue Native Server Renderer'
  ],
  React: [
    'React',
    'React Router',
    'React Redux',
    'React Native',
    'React Native Router',
    'React Native Redux',
    'React Native Test Utils',
    'React Native Server Renderer'
  ],
  'Node.js': [
    'Node.js',
    'Express',
    'Koa',
    'Nest',
    'Fastify',
    'Hapi',
    'Restify',
    'Socket.io',
    'Webpack',
    'Gulp',
    'Grunt',
    'Yeoman',
    'Bower',
    'npm',
    'yarn',
    'pnpm',
    'webpack',
    'gulp',
    'grunt',
    'yeoman',
    'bower',
    'npm',
    'yarn',
    'pnpm'
  ],
  Angular: [
    'Angular',
    'Angular Router',
    'Angular Redux',
    'Angular Native',
    'Angular Native Router',
    'Angular Native Redux',
    'Angular Native Test Utils',
    'Angular Native Server Renderer'
  ],
  jQuery: [
    'jQuery',
    'jQuery UI',
    'jQuery Mobile',
    'jQuery Plugins',
    'jQuery Test Utils',
    'jQuery Server Renderer'
  ],
  Bootstrap: [
    'Bootstrap',
    'Bootstrap 4',
    'Bootstrap 5',
    'Bootstrap Plugins',
    'Bootstrap Test Utils',
    'Bootstrap Server Renderer'
  ],
  'Tailwind CSS': [
    'Tailwind CSS',
    'Tailwind CSS Plugins',
    'Tailwind CSS Test Utils',
    'Tailwind CSS Server Renderer'
  ],
  Webpack: ['Webpack', 'Webpack Plugins', 'Webpack Test Utils', 'Webpack Server Renderer'],
  Gulp: ['Gulp', 'Gulp Plugins', 'Gulp Test Utils', 'Gulp Server Renderer'],
  Grunt: ['Grunt', 'Grunt Plugins', 'Grunt Test Utils', 'Grunt Server Renderer']
}
